const {chromium}=require(require('child_process').execSync('npm root -g').toString().trim()+'/playwright');
(async()=>{const b=await chromium.launch();const ctx=await b.newContext({viewport:{width:1440,height:900},deviceScaleFactor:2});const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));await p.route(/jsdelivr/,r=>r.abort());
 await p.clock.setFixedTime(new Date('2026-09-30T10:00:00'));
 await p.goto('file://'+process.cwd()+'/v73.html');await p.waitForTimeout(1200);
 const dev=p.locator('.home-only-device');
 const cap=async(n)=>{await p.waitForTimeout(700);await dev.screenshot({path:`pfcap/${n}.png`});console.log('cap',n)};
 const txt=()=>p.evaluate(()=>document.querySelector('#root').innerText.replace(/\s+/g,' ').slice(0,160));
 await p.getByText('건너뛰기').click();await p.waitForTimeout(400);
 await p.getByText('기록하기').first().click();await cap('07-1');
 const cb=await p.locator('.app-home-compass-v43').first().boundingBox();await p.mouse.click(cb.x+cb.width*.38,cb.y+cb.height*.36);await p.waitForTimeout(400);
 console.log('sel',await p.evaluate(()=>document.querySelector('.app-home-main-grid-v43 .selected')?.textContent));
 await p.locator('.app-home-modal-next-v43').click();await p.waitForTimeout(500);
 console.log('words',await p.evaluate(()=>[...document.querySelectorAll('.app-home-sub-grid-v43 button')].map(b=>b.textContent)));
 await p.getByText('긴장되는',{exact:true}).click();await p.getByText('걱정되는',{exact:true}).click();await cap('07-2');
 await p.getByRole('button',{name:'다음',exact:true}).last().click();await p.waitForTimeout(500);
 await p.getByRole('textbox',{name:'오늘의 한 문장'}).fill('중요한 일을 앞두고 실수하지 않으려 계속 확인했다.');await p.locator('body').click({position:{x:5,y:5}});await cap('07-3');
 await p.getByRole('button',{name:'저장하기',exact:true}).click();await cap('07-4');
 await p.locator('nav button').filter({hasText:'창작소'}).click();await cap('08-1');
 await p.getByText('한 장의 그림으로').click();await cap('08-2');
 await p.getByRole('button',{name:'다음',exact:true}).last().click();await cap('08-3');
 await p.getByRole('button',{name:'이 재료로 만들기'}).click();await p.waitForTimeout(1500);
 if(await p.getByRole('button',{name:'결과 바로 보기'}).count())await p.getByRole('button',{name:'결과 바로 보기'}).click();
 await cap('08-4');
 await p.getByRole('button',{name:'컬러 라인 포스터'}).click();await cap('09-1');
 await p.getByRole('button',{name:'그림일기'}).click();await p.waitForTimeout(300);
 await p.getByRole('button',{name:'저장하기',exact:true}).click();await p.waitForTimeout(600);
 console.log(await txt());
 await p.getByRole('button',{name:'홈으로'}).click();await p.waitForTimeout(400);
 await p.locator('nav button').filter({hasText:'아카이브'}).click();await p.waitForTimeout(500);
 await p.getByText('월간',{exact:true}).first().click();await cap('10-1');
 await p.getByText('나의 창작물').first().click();await cap('10-2');
 console.log(await txt());
 const work=p.locator('.my-creation-grid button, .archive-day-creations button').filter({has:p.locator('img')}).first();
 console.log('works',await work.count());await work.click();await cap('10-3');console.log(await txt());
 await p.getByRole('button',{name:/굿즈 미리보기/}).click();await cap('10-4');console.log(await txt());
 console.log('errs',errs);await b.close()})();
